language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-add-repository -y ppa:canonical-qt5-edgers/qt5-proper
  - sudo apt-get update
  - sudo apt-get install qtdeclarative5-dev
  - sudo apt-get install libqt5webkit5-dev
script:
  - /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -v
  - /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  - make
branches:
  only:
    - master
    - develop
notifications:
  irc: 
    channels:
      - "chat.freenode.net#wirk"
    template:
      - "%{author} committed %{commit} to %{branch}: %{commit_message}."
      - "%{compare_url}"
      - "Build #%{build_number} of %{repository}.  Status: %{message}" 
      - "%{build_url}"